// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx40X9j8dKSw3jn4cLvM4_db_4V24ZhLo',
    appId: '1:982890941132:android:99051c920519f0d45c1069',
    messagingSenderId: '982890941132',
    projectId: 'flow-xz',
    storageBucket: 'flow-xz.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBXNZj-lmfHQLGZPUnwZz6VCvqnysxpzK8',
    appId: '1:982890941132:web:298be5960176e6225c1069',
    messagingSenderId: '982890941132',
    projectId: 'flow-xz',
    storageBucket: 'flow-xz.firebasestorage.app',
    authDomain: 'flow-xz.firebaseapp.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrngI8iEZaUn-uvcSniV0wP0Kk5pidXq8',
    appId: '1:982890941132:ios:2d6a80b7111c17325c1069',
    messagingSenderId: '982890941132',
    projectId: 'flow-xz',
    storageBucket: 'flow-xz.firebasestorage.app',
    iosClientId:
        '982890941132-0d3acvft2h7vjjbq2ntjppgf15019ivj.apps.googleusercontent.com',
    iosBundleId: 'com.example.redesigned',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXNZj-lmfHQLGZPUnwZz6VCvqnysxpzK8',
    appId: '1:982890941132:web:298be5960176e6225c1069',
    messagingSenderId: '982890941132',
    projectId: 'flow-xz',
    authDomain: 'flow-xz.firebaseapp.com',
    storageBucket: 'flow-xz.firebasestorage.app',
    measurementId: 'G-KY314F881C',
  );
}
